// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfPatternEntry struct {
	_           structs.HostLayout
	Original    [16]int8
	Replacement [16]int8
	Len         uint32
	Active      uint32
}

type bpfReadInfo struct {
	_      structs.HostLayout
	BufPtr uint64
	Count  uint64
	Fd     int64
}

type bpfScratchData struct {
	_    structs.HostLayout
	Data [4096]int8
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	HandleExit              *ebpf.ProgramSpec `ebpf:"handle_exit"`
	HandleFork              *ebpf.ProgramSpec `ebpf:"handle_fork"`
	TracepointSysEnterRead  *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_read"`
	TracepointSysEnterWrite *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_write"`
	TracepointSysExitRead   *ebpf.ProgramSpec `ebpf:"tracepoint_sys_exit_read"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	ActiveReads  *ebpf.MapSpec `ebpf:"active_reads"`
	PatternCount *ebpf.MapSpec `ebpf:"pattern_count"`
	Patterns     *ebpf.MapSpec `ebpf:"patterns"`
	ScratchBuf   *ebpf.MapSpec `ebpf:"scratch_buf"`
	TargetPidMap *ebpf.MapSpec `ebpf:"target_pid_map"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	UnusedPatternEntry *ebpf.VariableSpec `ebpf:"unused_pattern_entry"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	ActiveReads  *ebpf.Map `ebpf:"active_reads"`
	PatternCount *ebpf.Map `ebpf:"pattern_count"`
	Patterns     *ebpf.Map `ebpf:"patterns"`
	ScratchBuf   *ebpf.Map `ebpf:"scratch_buf"`
	TargetPidMap *ebpf.Map `ebpf:"target_pid_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.ActiveReads,
		m.PatternCount,
		m.Patterns,
		m.ScratchBuf,
		m.TargetPidMap,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	UnusedPatternEntry *ebpf.Variable `ebpf:"unused_pattern_entry"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	HandleExit              *ebpf.Program `ebpf:"handle_exit"`
	HandleFork              *ebpf.Program `ebpf:"handle_fork"`
	TracepointSysEnterRead  *ebpf.Program `ebpf:"tracepoint_sys_enter_read"`
	TracepointSysEnterWrite *ebpf.Program `ebpf:"tracepoint_sys_enter_write"`
	TracepointSysExitRead   *ebpf.Program `ebpf:"tracepoint_sys_exit_read"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.HandleExit,
		p.HandleFork,
		p.TracepointSysEnterRead,
		p.TracepointSysEnterWrite,
		p.TracepointSysExitRead,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
